In [ ]:
import re
from nltk.tokenize import word_tokenize
import string

In [ ]:
# Function to clean and tokenize text
def clean_and_tokenize(file_path):
    with open('next_word_prediction.txt', 'r', encoding='utf-8') as f:
        text = f.read()
    # Remove extra spaces
    text = re.sub(' +', ' ', text)
    # Remove extra blank lines
    text = re.sub('\\n+', '\\n', text)
    punctuation_except_full_stop = ''.join([ch for ch in string.punctuation if ch != '.'])
    text = text.translate(str.maketrans('', '', punctuation_except_full_stop))
    text = re.sub('”', '', text)
    text = re.sub('“', '', text)
    text = re.sub('’', '', text)
    text = re.sub('‘', '', text)
    text = re.sub('\\n', ' ', text)
    text = re.sub('\.\s', '.', text)
    text = text.lower()
    # text = text.split('.')
    return text

In [ ]:

file_path = '/content/next_word_prediction.txt'
text = clean_and_tokenize(file_path)
print(len(text))

554588


In [ ]:
import numpy as np
max([len(x) for x in text])

1

In [ ]:
text[1820]

't'

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts([text])

In [ ]:
total_words = len(tokenizer.word_index)

In [ ]:
total_words

8716

In [ ]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'i': 3,
 'of': 4,
 'to': 5,
 'a': 6,
 'in': 7,
 'that': 8,
 'it': 9,
 'you': 10,
 'he': 11,
 'was': 12,
 'his': 13,
 'is': 14,
 'my': 15,
 'have': 16,
 'with': 17,
 'as': 18,
 'had': 19,
 'at': 20,
 'which': 21,
 'for': 22,
 'not': 23,
 'but': 24,
 'be': 25,
 'me': 26,
 'we': 27,
 'this': 28,
 'from': 29,
 'there': 30,
 'said': 31,
 'upon': 32,
 'holmes': 33,
 'so': 34,
 'him': 35,
 'her': 36,
 'she': 37,
 'all': 38,
 'your': 39,
 'very': 40,
 'no': 41,
 'been': 42,
 'on': 43,
 'what': 44,
 'by': 45,
 'one': 46,
 'then': 47,
 'are': 48,
 'were': 49,
 'an': 50,
 'would': 51,
 'when': 52,
 'out': 53,
 'up': 54,
 'do': 55,
 'man': 56,
 'could': 57,
 'has': 58,
 'if': 59,
 'into': 60,
 'who': 61,
 'mr': 62,
 'or': 63,
 'little': 64,
 'will': 65,
 'some': 66,
 'now': 67,
 'see': 68,
 'down': 69,
 'our': 70,
 'should': 71,
 'may': 72,
 'they': 73,
 'well': 74,
 'am': 75,
 'us': 76,
 'over': 77,
 'can': 78,
 'about': 79,
 'more': 80,
 'think': 81,
 'must': 82,
 'shall':

In [ ]:
text = text.split('.')
input_sequences =[]
tokenized_sentence= tokenizer.texts_to_sequences(text)
for sentence in tokenized_sentence:
  if len(sentence)==1:
    sentence.append(0)
  for i in range(1,len(sentence)):
    input_sequences.append(sentence[:i+1])

In [ ]:
input_sequences

[[3, 0],
 [5, 127],
 [5, 127, 33],
 [5, 127, 33, 37],
 [5, 127, 33, 37, 14],
 [5, 127, 33, 37, 14, 214],
 [5, 127, 33, 37, 14, 214, 1],
 [5, 127, 33, 37, 14, 214, 1, 213],
 [3, 16],
 [3, 16, 1578],
 [3, 16, 1578, 111],
 [3, 16, 1578, 111, 35],
 [3, 16, 1578, 111, 35, 3237],
 [3, 16, 1578, 111, 35, 3237, 36],
 [3, 16, 1578, 111, 35, 3237, 36, 252],
 [3, 16, 1578, 111, 35, 3237, 36, 252, 86],
 [3, 16, 1578, 111, 35, 3237, 36, 252, 86, 88],
 [3, 16, 1578, 111, 35, 3237, 36, 252, 86, 88, 202],
 [7, 13],
 [7, 13, 140],
 [7, 13, 140, 37],
 [7, 13, 140, 37, 4587],
 [7, 13, 140, 37, 4587, 2],
 [7, 13, 140, 37, 4587, 2, 4588],
 [7, 13, 140, 37, 4587, 2, 4588, 1],
 [7, 13, 140, 37, 4587, 2, 4588, 1, 264],
 [7, 13, 140, 37, 4587, 2, 4588, 1, 264, 4],
 [7, 13, 140, 37, 4587, 2, 4588, 1, 264, 4, 36],
 [7, 13, 140, 37, 4587, 2, 4588, 1, 264, 4, 36, 4589],
 [9, 12],
 [9, 12, 23],
 [9, 12, 23, 8],
 [9, 12, 23, 8, 11],
 [9, 12, 23, 8, 11, 346],
 [9, 12, 23, 8, 11, 346, 86],
 [9, 12, 23, 8, 11, 346, 86,

In [ ]:
max_len = max([len(x) for x in input_sequences])

In [ ]:
max_len

101

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [ ]:
padded_input_sequences

array([[   0,    0,    0, ...,    0,    3,    0],
       [   0,    0,    0, ...,    0,    5,  127],
       [   0,    0,    0, ...,    5,  127,   33],
       ...,
       [   0,    0,    0, ...,    5,  339,   79],
       [   0,    0,    0, ...,  339,   79,  336],
       [   0,    0,    0, ...,   79,  336, 1575]], dtype=int32)

In [ ]:
X = padded_input_sequences[:,:-1]

In [ ]:
y = padded_input_sequences[:,-1]

In [ ]:
X.shape,y.shape

((101357, 100), (101357,))

In [ ]:
X

array([[   0,    0,    0, ...,    0,    0,    3],
       [   0,    0,    0, ...,    0,    0,    5],
       [   0,    0,    0, ...,    0,    5,  127],
       ...,
       [   0,    0,    0, ..., 8716,    5,  339],
       [   0,    0,    0, ...,    5,  339,   79],
       [   0,    0,    0, ...,  339,   79,  336]], dtype=int32)

In [ ]:
y

array([   0,  127,   33, ...,   79,  336, 1575], dtype=int32)

In [ ]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=total_words+1)

In [ ]:
y.shape

(101357, 8717)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [ ]:
model = Sequential()
model.add(Embedding(total_words+1, 100, input_length=100))
model.add(LSTM(200))
# model.add(LSTM(1))
model.add(Dense(total_words+1, activation='softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 100, 100)          871700    
                                                                 
 lstm (LSTM)                 (None, 200)               240800    
                                                                 
 dense (Dense)               (None, 8717)              1752117   
                                                                 
Total params: 2864617 (10.93 MB)
Trainable params: 2864617 (10.93 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [29]:
model.fit(X,y,epochs=50,batch_size = 64)

Epoch 1/50
1584/1584 [==============================] - 61s 36ms/step - loss: 6.3695 - accuracy: 0.0781
Epoch 2/50
1584/1584 [==============================] - 30s 19ms/step - loss: 5.5746 - accuracy: 0.1278
Epoch 3/50
1584/1584 [==============================] - 26s 17ms/step - loss: 5.1725 - accuracy: 0.1479
Epoch 4/50
1584/1584 [==============================] - 26s 16ms/step - loss: 4.8317 - accuracy: 0.1664
Epoch 5/50
1584/1584 [==============================] - 25s 16ms/step - loss: 4.5142 - accuracy: 0.1836
Epoch 6/50
1584/1584 [==============================] - 25s 16ms/step - loss: 4.2143 - accuracy: 0.2029
Epoch 7/50
1584/1584 [==============================] - 25s 16ms/step - loss: 3.9279 - accuracy: 0.2270
Epoch 8/50
1584/1584 [==============================] - 25s 16ms/step - loss: 3.6590 - accuracy: 0.2585
Epoch 9/50
1584/1584 [==============================] - 26s 16ms/step - loss: 3.4079 - accuracy: 0.2942
Epoch 10/50
1584/1584 [==============================] - 25s 16m

In [32]:
import time
text = "hi"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=100, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      # time.sleep(1)

1/1 [==============================] - 0s 18ms/step
hi how
1/1 [==============================] - 0s 17ms/step
hi how could
1/1 [==============================] - 0s 18ms/step
hi how could it
1/1 [==============================] - 0s 18ms/step
hi how could it be
1/1 [==============================] - 0s 18ms/step
hi how could it be as
1/1 [==============================] - 0s 17ms/step
hi how could it be as if
1/1 [==============================] - 0s 19ms/step
hi how could it be as if your
1/1 [==============================] - 0s 18ms/step
hi how could it be as if your hair
1/1 [==============================] - 0s 28ms/step
hi how could it be as if your hair would
1/1 [==============================] - 0s 37ms/step
hi how could it be as if your hair would mean


In [33]:
model.save('next_word_model.h5',include_optimizer=True)

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
